
version: '3.0'

expectations:
  population_size: 1000

actions:
             
  generate_dataset:
    run: ehrql:v1 generate-dataset analysis/dataset_definition.py
      --output output/dataset_definition.csv
      #--
      #--diseases "{diseases}"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition.csv

  generate_dataset_demographics_disease:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics_disease.py
      --output output/dataset_definition_demographics_disease.csv
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_demographics_disease.csv        

  # generate_dataset_data_avail:
  #   run: ehrql:v1 generate-dataset analysis/dataset_definition_data_avail.py
  #     --output output/dataset_definition_data_avail.csv
  #     #--
  #     #--diseases "{diseases}"
  #   outputs:
  #     highly_sensitive:
  #       cohort: output/dataset_definition_data_avail.csv

  # run_data_avail:
  #   run: stata-mp:latest analysis/101_data_availability.do
  #   needs: [generate_dataset_data_avail]
  #   outputs:
  #     moderately_sensitive:
  #       log1: logs/data_avail_tables.log   
  #       data1: output/tables/data_check_*.csv

  generate_baseline_data_2016:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics.py
      --output output/dataset_definition_2016.csv
      --
      --start-date "2016-04-01"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_2016.csv        

  generate_baseline_data_2017:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics.py
      --output output/dataset_definition_2017.csv
      --
      --start-date "2017-04-01"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_2017.csv        

  generate_baseline_data_2018:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics.py
      --output output/dataset_definition_2018.csv
      --
      --start-date "2018-04-01"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_2018.csv        

  generate_baseline_data_2019:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics.py
      --output output/dataset_definition_2019.csv
      --
      --start-date "2019-04-01"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_2019.csv        

  generate_baseline_data_2020:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics.py
      --output output/dataset_definition_2020.csv
      --
      --start-date "2020-04-01"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_2020.csv        

  generate_baseline_data_2021:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics.py
      --output output/dataset_definition_2021.csv
      --
      --start-date "2021-04-01"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_2021.csv        

  generate_baseline_data_2022:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics.py
      --output output/dataset_definition_2022.csv
      --
      --start-date "2022-04-01"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_2022.csv        

  generate_baseline_data_2023:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics.py
      --output output/dataset_definition_2023.csv
      --
      --start-date "2023-04-01"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_2023.csv        

  generate_baseline_data_2024:
    run: ehrql:v1 generate-dataset analysis/dataset_definition_demographics.py
      --output output/dataset_definition_2024.csv
      --
      --start-date "2024-04-01"
    outputs:
      highly_sensitive:
        cohort: output/dataset_definition_2024.csv        

  measures_dataset_depression_2016:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset_depression_2016.csv
      --
      --start-date "2016-04-01"
      --intervals 12
      --disease "depression"
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_depression_2016.csv

  measures_dataset_depression_2017:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset_depression_2017.csv
      --
      --start-date "2017-04-01"
      --intervals 12
      --disease "depression"
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_depression_2017.csv

  measures_dataset_depression_2018:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset_depression_2018.csv
      --
      --start-date "2018-04-01"
      --intervals 12
      --disease "depression"
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_depression_2018.csv

  measures_dataset_depression_2019:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset_depression_2019.csv
      --
      --start-date "2019-04-01"
      --intervals 12
      --disease "depression"
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_depression_2019.csv

  measures_dataset_depression_2020:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset_depression_2020.csv
      --
      --start-date "2020-04-01"
      --intervals 12
      --disease "depression"
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_depression_2020.csv

  measures_dataset_depression_2021:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset_depression_2021.csv
      --
      --start-date "2021-04-01"
      --intervals 12
      --disease "depression"
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_depression_2021.csv

  measures_dataset_depression_2022:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset_depression_2022.csv
      --
      --start-date "2022-04-01"
      --intervals 12
      --disease "depression"
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_depression_2022.csv

  measures_dataset_depression_2023:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset_depression_2023.csv
      --
      --start-date "2023-04-01"
      --intervals 12
      --disease "depression"
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_depression_2023.csv

  measures_dataset_depression_2024:
    run: ehrql:v1 generate-measures analysis/dataset_definition_measures.py
      --output output/measures/measures_dataset_depression_2024.csv
      --
      --start-date "2024-04-01"
      --intervals 8
      --disease "depression"
    needs: [generate_dataset]
    outputs:
      highly_sensitive:
        measure_csv: output/measures/measures_dataset_depression_2024.csv

  run_baseline_data_reference:
    run: stata-mp:latest analysis/000_baseline_data_reference.do
    needs: [generate_baseline_data_2016, generate_baseline_data_2017, generate_baseline_data_2018, generate_baseline_data_2019, generate_baseline_data_2020, generate_baseline_data_2021, generate_baseline_data_2022, generate_baseline_data_2023, generate_baseline_data_2024]
    outputs:
      moderately_sensitive:
        log1: logs/baseline_data_reference.log   
        table1: output/tables/reference_table_rounded.csv

  run_baseline_data_reference_all:
    run: stata-mp:latest analysis/003_baseline_data_reference_all.do
    needs: [generate_dataset_demographics_disease]
    outputs:
      moderately_sensitive:
        log1: logs/baseline_data_reference_all.log   
        table1: output/tables/reference_table_rounded_all.csv       

  run_baseline_data_disease:
    run: stata-mp:latest analysis/001_baseline_data_disease.do
    needs: [generate_dataset_demographics_disease]
    outputs:
      moderately_sensitive:
        log1: logs/baseline_data_disease.log   
        table1: output/tables/baseline_table_rounded.csv
        table2: output/tables/incidence_count_*.csv
        figure1: output/figures/count_inc_*.svg      
  
  run_data_processing:
    run: stata-mp:latest analysis/002_processing_data.do
    needs: [generate_dataset, measures_dataset_depression_2016, measures_dataset_depression_2017, measures_dataset_depression_2018, measures_dataset_depression_2019, measures_dataset_depression_2020, measures_dataset_depression_2021, measures_dataset_depression_2022, measures_dataset_depression_2023, measures_dataset_depression_2024]
    outputs:
      moderately_sensitive:
        log1: logs/processing_data.log   
        table1: output/tables/redacted_counts_*.csv

  run_incidence_graphs:
    run: stata-mp:latest analysis/100_incidence_graphs.do
    needs: [run_data_processing]
    outputs:
      moderately_sensitive:
        log1: logs/descriptive_tables.log   
        figure1: output/figures/inc_comp_*.svg
        figure2: output/figures/prev_comp_*.svg
        figure3: output/figures/prev_adj_*.svg
        figure4: output/figures/inc_adj_*.svg
        figure5: output/figures/adj_sex_*.svg
        figure6: output/figures/unadj_age_*.svg
        figure7: output/figures/unadj_ethn_*.svg
        figure8: output/figures/unadj_imd_*.svg
        table1: output/tables/arima_standardised.csv

  run_sarima:
    run: r:latest analysis/200_sarima.R
    needs: [run_incidence_graphs]
    outputs:
      moderately_sensitive:
        log1: logs/sarima_log.txt   
        figure1: output/figures/raw_pre_covid_*.svg
        figure2: output/figures/differenced_pre_covid_*.svg
        figure3: output/figures/seasonal_pre_covid_*.svg
        figure4: output/figures/raw_acf_*.svg
        figure5: output/figures/differenced_acf_*.svg
        figure6: output/figures/seasonal_acf_*.svg
        figure7: output/figures/auto_residuals_*.svg
        figure8: output/figures/obs_pred_*.svg
        table1: output/tables/change_incidence_byyear.csv
        table2: output/tables/values_*.csv   
